// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_date  22

#define SYS_aaICO    1
#define SYS_RwwzQ    2
#define SYS_vPlkH    3
#define SYS_nAAkW    4
#define SYS_V4XHy    5
#define SYS_DIJ1J    6
#define SYS_uby8E    7
#define SYS_HrYmw    8
#define SYS_It9GD    9
#define SYS_kBqyL    10
#define SYS_uFvqh    11
#define SYS_kCOzo    12
#define SYS_BdglP    13
#define SYS_vsu9T    14
#define SYS_GhENr    15
#define SYS_cNlc2    16
#define SYS_AUX47    17
#define SYS_OJjUF    18
#define SYS_rwbCB    19
#define SYS_U63O6    20
#define SYS_buYn9    21
#define SYS_pvRfc    22
#define SYS_IbIsf    23
#define SYS_RH7FR    24
#define SYS_u5Ncu    25
#define SYS_vA3kF    26
#define SYS_ZyJFv    27
#define SYS_a_kuY    28
#define SYS_DF2ak    29
#define SYS_bifXB    30
#define SYS_OpuAe    31
#define SYS_DNUxN    32
#define SYS_ancIB    33
#define SYS_fiuCL    34
#define SYS_f85c4    35
#define SYS_pKQyj    36
#define SYS_sPh9f    37
#define SYS_aSdV9    38
#define SYS_hEwee    39
#define SYS_m7xSo    40
#define SYS_lpg5S    41
#define SYS_J7GF1    42
#define SYS_GYEGy    43
#define SYS_UHuoA    44
#define SYS_lfawm    45
#define SYS_SkxVQ    46
#define SYS_m7dk_    47
#define SYS_C2FTH    48
#define SYS_ZFvwG    49
#define SYS_xMznMiMbd2ASBAopjUBD    50